### ISSUE TITLE
运行错误，提示：ModuleNotFoundError: No module named 'ruamel'

### ISSUE THREAD

**Issue by gudaoxongdi** [rinkky/ineedmask#1]
详细是这样：
RESTART: C:\Users\Administrator\Downloads\ineedmask-master\ineedmask-master\run.py 
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\ineedmask-master\ineedmask-master\checker\check_store.py", line 3, in <module>
    from alert import alert
  File "C:\Users\Administrator\Downloads\ineedmask-master\ineedmask-master\alert\__init__.py", line 1, in <module>
    from config.logger import logger
  File "C:\Users\Administrator\Downloads\ineedmask-master\ineedmask-master\config\__init__.py", line 2, in <module>
    from ruamel import yaml
ModuleNotFoundError: No module named 'ruamel'

请问要怎么办？

**Comment by rinkky** [comment]
缺少依赖。更新代码然后运行`pip install -r requirements.txt`.
